"""settings

Revision ID: 24febb70e661
Revises: 5d8fdf9bbb9c
Create Date: 2024-10-05 00:38:54.828046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24febb70e661'
down_revision = '5d8fdf9bbb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
